/**
 * Wizard artwork for the KORA Market installer.
 *
 * Purely geometric: the approved K monogram and a hairline on the app's own #0A0A0A. Text is
 * deliberately absent — the three prototype faces are bundled with the app but not installed
 * on this machine, so any wordmark rendered here would be silently substituted with whatever
 * fontconfig picked, and a wrong typeface on the first screen of the installer is worse than
 * no typeface at all.
 *
 * PNG rather than BMP: Inno Setup accepts PNG from 6.5.0 and we build with 6.7.3, which
 * sidesteps 24-bit BGR bitmap authoring entirely.
 */

import { mkdir, writeFile } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'
import { dirname, join, resolve } from 'node:path'
import sharp from 'sharp'

const OUT = resolve(dirname(fileURLToPath(import.meta.url)), '../../../MARKET/installer')

const BG = '#0a0a0a'
const INK = '#f0f0f0'
const LINE = '#232323'

/** The approved monogram, at a given size within a viewBox of its own. */
const mark = (x, y, size, colour = INK) => {
  const k = size / 64
  return `<g transform="translate(${x} ${y}) scale(${k})" fill="${colour}">
    <rect x="17" y="16" width="7" height="32"/>
    <path d="M28 32 L45 16 L45 25 L37 32 L45 39 L45 48 Z"/>
  </g>`
}

/** The tall panel on the welcome and finished pages. Authored at 164x314 and scaled up. */
function tall(w, h) {
  const s = w / 164 // the ratio Inno fixes for this image
  const markSize = 62
  return `<svg xmlns="http://www.w3.org/2000/svg" width="${w}" height="${h}" viewBox="0 0 164 314">
    <rect width="164" height="314" fill="${BG}"/>
    ${mark((164 - markSize) / 2, 104, markSize)}
    <!--
      One completed rule, not a partly-filled rail. The splash animates a hairline from zero
      to full width; frozen into a still image that same shape reads as a progress bar stuck
      at a third, which is exactly how it was reported.
    -->
    <rect x="37" y="196" width="90" height="1" fill="${INK}"/>
    <g fill="${LINE}">
      <rect x="0" y="0" width="164" height="1"/>
      <rect x="0" y="313" width="164" height="1"/>
    </g>
    <!-- scale marker keeps the renderer honest about units -->
    <rect x="0" y="0" width="0" height="0" opacity="0" transform="scale(${s})"/>
  </svg>`
}

/** The small mark in the header band of every inner page. */
function small(size) {
  return `<svg xmlns="http://www.w3.org/2000/svg" width="${size}" height="${size}" viewBox="0 0 64 64">
    <rect width="64" height="64" fill="${BG}"/>
    ${mark(0, 0, 64)}
  </svg>`
}

async function render(svg, file) {
  // No alpha: the installer composites these onto its own background, and a transparent edge
  // would let the wizard's own colour bleed through the artwork.
  await sharp(Buffer.from(svg))
    .flatten({ background: BG })
    .png({ compressionLevel: 9 })
    .toFile(join(OUT, file))
  return file
}

await mkdir(OUT, { recursive: true })

// The DPI ladder Inno picks from: it takes the closest match to the current scaling.
const TALL = [
  [202, 386], [269, 515], [336, 643], [430, 824], [534, 1022],
]
const SMALL = [58, 83, 110, 159]

const written = []
for (const [w, h] of TALL) written.push(await render(tall(w, h), `wizard-${w}x${h}.png`))
for (const s of SMALL) written.push(await render(small(s), `wizard-small-${s}.png`))

await writeFile(
  join(OUT, 'README.txt'),
  'Generated by tools/branding/wizard-art.mjs. Do not edit by hand — regenerate instead.\n',
)

console.log(written.join('\n'))
console.log(`\n${written.length} files in ${OUT}`)
