; KORA Market — Windows installer
;
; Market only. This is deliberately not the combined Suite script: Market is its own product
; with its own AppId, so it installs, upgrades and uninstalls without touching a Kora Wallet
; that may already be on the machine.
;
; The wizard is restyled to the app's own look — #0A0A0A, square corners, monochrome — in the
; [Code] section below. That work is done by hand because Inno's own theming cannot reach it:
; with a custom WizardStyle keyword active, VCL Styles take over and colours set from Pascal
; Scripting are ignored. The two approaches are mutually exclusive, so this uses plain
; "modern" and repaints every control itself.
;
; Build:  flutter build windows --release
; Then:   ISCC.exe installer_market.iss

#define AppName      "KORA Market"
#define AppVersion   "5.1.1"
#define AppPublisher "Nahreba Mykhailo"
#define AppExeName   "kora_widget.exe"
#define BuildDir     "build\windows\x64\runner\Release"

[Setup]
; A GUID of its own. Reusing the Wallet's would make the two products overwrite each other.
AppId={{7C3E1A94-6B2D-4F58-9E71-2A5D8C0F3B14}
AppName={#AppName}
AppVersion={#AppVersion}
AppVerName={#AppName} {#AppVersion}
AppPublisher={#AppPublisher}
DefaultDirName={autopf}\{#AppName}
DefaultGroupName={#AppName}
AllowNoIcons=yes
OutputDir=installer_output
OutputBaseFilename=KoraMarket_Setup_v{#AppVersion}
SetupIconFile=..\windows\runner\resources\installer_icon.ico
UninstallDisplayIcon={app}\{#AppExeName}
Compression=lzma2/ultra64
SolidCompression=yes
DisableDirPage=no
DisableProgramGroupPage=no
MinVersion=10.0
; Per-user, with no mode dialog.
;
; PrivilegesRequiredOverridesAllowed=dialog puts a stock "Select Setup Install Mode" window
; on screen BEFORE InitializeWizard runs — so it is the one surface the dark theming below
; can never reach, and it would be the first thing anyone sees. A per-user install needs
; neither the choice nor an elevation prompt.
PrivilegesRequired=lowest
ArchitecturesInstallIn64BitMode=x64compatible
ArchitecturesAllowed=x64compatible

; Plain "modern" is required — see the header note. The welcome page is switched back on
; because it is the only page that shows the tall artwork, and skipping it would mean the
; installer's own identity never appeared.
WizardStyle=modern
DisableWelcomePage=no

; A DPI ladder; Setup picks the closest match. The artwork is generated by
; WALLET/tools/branding/wizard-art.mjs and carries its dark background baked in — WizardImageBackColor
; only paints around a bitmap, so light stock artwork would show as a white block.
WizardImageFile=installer\wizard-202x386.png,installer\wizard-269x515.png,installer\wizard-336x643.png,installer\wizard-430x824.png,installer\wizard-534x1022.png
WizardSmallImageFile=installer\wizard-small-58.png,installer\wizard-small-83.png,installer\wizard-small-110.png,installer\wizard-small-159.png
WizardImageAlphaFormat=none
WizardImageStretch=yes
WizardImageBackColor=$000A0A0A

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"

[Files]
Source: "{#BuildDir}\{#AppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#BuildDir}\*.dll"; DestDir: "{app}"; Flags: ignoreversion skipifsourcedoesntexist
Source: "{#BuildDir}\data\*"; DestDir: "{app}\data"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{group}\{#AppName}"; Filename: "{app}\{#AppExeName}"
Name: "{group}\{cm:UninstallProgram,{#AppName}}"; Filename: "{uninstallexe}"
Name: "{autodesktop}\{#AppName}"; Filename: "{app}\{#AppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#AppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(AppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

[UninstallDelete]
Type: filesandordirs; Name: "{app}\data"

; ============================================================================
;  Dark / square / monochrome wizard
; ============================================================================
[Code]

{ TColor is $00BBGGRR. Every value here is a neutral grey, so the red/blue swap is a no-op;
  a non-grey accent would have to be byte-swapped by hand. }
const
  clBg      = $000A0A0A;  { #0A0A0A  page and form background          }
  clSurface = $00111111;  { #111111  fields, buttons, progress track   }
  clFg      = $00F0F0F0;  { #F0F0F0  text, progress fill               }
  clFgMuted = $008A8A8A;  { #8A8A8A  disabled text                     }
  clLine    = $00232323;  { the 10% hairline, flattened onto #0A0A0A   }

  DWMWA_USE_IMMERSIVE_DARK_MODE_OLD = 19;   { Win10 17763..18984 }
  DWMWA_USE_IMMERSIVE_DARK_MODE     = 20;   { Win10 18985+       }
  DWMWA_WINDOW_CORNER_PREFERENCE    = 33;   { Win11 22000+       }
  DWMWCP_DONOTROUND                 = 1;

  PBM_SETBKCOLOR  = $2001;
  PBM_SETBARCOLOR = $0409;
  PBS_SMOOTH      = $01;
  BM_CLICK        = $00F5;

  GWL_STYLE        = -16;
  GWL_EXSTYLE      = -20;
  WS_BORDER        = $00800000;
  WS_EX_CLIENTEDGE = $00000200;
  WS_EX_STATICEDGE = $00020000;
  SWP_NOSIZE = $01; SWP_NOMOVE = $02; SWP_NOZORDER = $04;
  SWP_NOACTIVATE = $10; SWP_FRAMECHANGED = $20;

  OFFSCREEN_TOP = 30000;

{ delayload: the DLLs are opened on first call, so a missing one can never abort Setup at
  startup. No setuponly flag — these are called from the uninstaller's form too.
  SendMessage and PostMessage are built in; GetWindowLong, SetWindowLong and SetWindowPos
  are not, hence the Api* imports. }
function DwmSetWindowAttribute(hwnd: HWND; dwAttribute: Cardinal;
  var pvAttribute: Integer; cbAttribute: Cardinal): Integer;
  external 'DwmSetWindowAttribute@dwmapi.dll stdcall delayload';

function SetWindowTheme(hwnd: HWND; pszSubAppName, pszSubIdList: WideString): Integer;
  external 'SetWindowTheme@uxtheme.dll stdcall delayload';

function ApiSetWindowPos(hWnd, hWndInsertAfter: HWND; X, Y, cx, cy: Integer;
  uFlags: Cardinal): Integer;
  external 'SetWindowPos@user32.dll stdcall';

function ApiGetWindowLong(hWnd: HWND; nIndex: Integer): Longint;
  external 'GetWindowLongW@user32.dll stdcall';

function ApiSetWindowLong(hWnd: HWND; nIndex: Integer; dwNewLong: Longint): Longint;
  external 'SetWindowLongW@user32.dll stdcall';

var
  GBtnReal: array of TNewButton;   { the real buttons, parked off-screen }
  GBtnFace: array of TPanel;       { the visible dark square             }
  GBtnText: array of TLabel;       { its caption                         }
  GLines: array of TPanel;         { our own hairlines and button outlines }

{ ---- square corners and dark caption ------------------------------------- }

function WinBuild: Cardinal;
var
  V: TWindowsVersion;
begin
  GetWindowsVersionEx(V);
  if V.NTPlatform then
    Result := V.Build
  else
    Result := 0;
end;

{ Triple-guarded so it cannot break an older Windows: a build gate, delayload, and a try.
  On Windows 10 attribute 33 would merely return E_INVALIDARG, but the gate stops it being
  sent at all. }
procedure ApplyDwm(H: HWND);
var
  V: Integer;
  B: Cardinal;
begin
  if H = 0 then
    Exit;
  B := WinBuild;
  try
    if B >= 18985 then begin
      V := 1;
      DwmSetWindowAttribute(H, DWMWA_USE_IMMERSIVE_DARK_MODE, V, SizeOf(V));
    end else if B >= 17763 then begin
      V := 1;
      DwmSetWindowAttribute(H, DWMWA_USE_IMMERSIVE_DARK_MODE_OLD, V, SizeOf(V));
    end;
    if B >= 22000 then begin
      V := DWMWCP_DONOTROUND;
      DwmSetWindowAttribute(H, DWMWA_WINDOW_CORNER_PREFERENCE, V, SizeOf(V));
    end;
  except
    { attribute unsupported on this OS — ignore }
  end;
end;

{ ---- low level helpers ---------------------------------------------------- }

{ Removes the themed 3D frame from an edit, memo or rich edit. }
procedure StripBorder(WC: TWinControl);
var
  L: Longint;
begin
  L := ApiGetWindowLong(WC.Handle, GWL_EXSTYLE);
  ApiSetWindowLong(WC.Handle, GWL_EXSTYLE,
    L and (not WS_EX_CLIENTEDGE) and (not WS_EX_STATICEDGE));
  L := ApiGetWindowLong(WC.Handle, GWL_STYLE);
  ApiSetWindowLong(WC.Handle, GWL_STYLE, L and (not WS_BORDER));
  ApiSetWindowPos(WC.Handle, 0, 0, 0, 0, 0,
    SWP_NOMOVE or SWP_NOSIZE or SWP_NOZORDER or SWP_NOACTIVATE or SWP_FRAMECHANGED);
end;

procedure DarkScrollbars(WC: TWinControl);
begin
  try
    SetWindowTheme(WC.Handle, 'DarkMode_Explorer', '');
  except
  end;
end;

{ Removes the visual style from a control so its own Color and Font are honoured again. }
procedure DeTheme(WC: TWinControl);
begin
  try
    SetWindowTheme(WC.Handle, ' ', ' ');
  except
  end;
end;

{ A themed TPanel paints its parent's background and silently ignores Color, which is why an
  earlier pass produced buttons that were only legible because their text was light on an
  unpainted panel — the moment the primary button's text went dark it vanished entirely.
  ParentBackground must be off before Color means anything. }
procedure SolidPanel(P: TPanel; AColor: TColor);
begin
  P.BevelOuter := bvNone;
  P.BevelKind := bkNone;
  P.ParentBackground := False;
  P.Color := AColor;
end;

{ Remembers a panel of ours so a later repaint pass can put its colour back. }
procedure RememberLine(P: TPanel);
var
  N: Integer;
begin
  N := GetArrayLength(GLines);
  SetArrayLength(GLines, N + 1);
  GLines[N] := P;
end;

function NewLine(AParent: TWinControl; L, T, W, H: Integer): TPanel;
begin
  Result := TPanel.Create(AParent);
  Result.Parent := AParent;
  SolidPanel(Result, clLine);
  Result.SetBounds(L, T, W, H);
  RememberLine(Result);
end;

{ A one-pixel hairline behind a control, in place of the themed border. }
procedure Frame1px(C: TControl);
var
  P: TPanel;
begin
  if C.Parent = nil then
    Exit;
  P := NewLine(C.Parent, C.Left - 1, C.Top - 1, C.Width + 2, C.Height + 2);
  P.SendToBack;
  C.BringToFront;
end;

{ The progress bar ignores Color because it is a themed comctl32 control. Killing the theme
  first makes PBM_SETBKCOLOR and PBM_SETBARCOLOR take effect; progress reporting is untouched. }
procedure StyleProgressBar(PB: TNewProgressBar);
var
  L: Longint;
begin
  try
    SetWindowTheme(PB.Handle, ' ', ' ');
  except
  end;
  L := ApiGetWindowLong(PB.Handle, GWL_STYLE);
  ApiSetWindowLong(PB.Handle, GWL_STYLE, L or PBS_SMOOTH);
  SendMessage(PB.Handle, PBM_SETBKCOLOR, 0, clSurface);
  SendMessage(PB.Handle, PBM_SETBARCOLOR, 0, clFg);
end;

{ ---- pass A: recolour every control --------------------------------------- }
{ TControl publishes neither Color nor Font, so a generic walk still needs one branch per
  class. These cover every control the stock wizard and uninstall form contain. }

procedure PaintTree(P: TWinControl); forward;

procedure PaintOne(C: TControl);
begin
  if C is TNewProgressBar then begin
    StyleProgressBar(TNewProgressBar(C));
  end else if C is TBevel then begin
    C.Visible := False;            { a TBevel's colour is not settable — hide it }
  end else if C is TNewButton then begin
    { skinned in pass B }
  end else if C is TBitmapImage then begin
    TBitmapImage(C).BackColor := clBg;
  end else if C is TNewCheckListBox then begin
    TNewCheckListBox(C).Color := clBg;
    TNewCheckListBox(C).Font.Color := clFg;
    TNewCheckListBox(C).BorderStyle := bsNone;
    DarkScrollbars(TNewCheckListBox(C));
  end else if C is TNewListBox then begin
    TNewListBox(C).Color := clSurface;
    TNewListBox(C).Font.Color := clFg;
    TNewListBox(C).BorderStyle := bsNone;
    DarkScrollbars(TNewListBox(C));
  end else if C is TRichEditViewer then begin
    TRichEditViewer(C).Color := clSurface;
    TRichEditViewer(C).Font.Color := clFg;
    StripBorder(TRichEditViewer(C));
    DarkScrollbars(TRichEditViewer(C));
  end else if C is TNewMemo then begin
    TNewMemo(C).Color := clSurface;
    TNewMemo(C).Font.Color := clFg;
    StripBorder(TNewMemo(C));
    DarkScrollbars(TNewMemo(C));
  end else if C is TNewEdit then begin
    { Same theme trap as the checkbox: a themed EDIT paints its own white client area and
      ignores Color. It read as fixed on the directory page only because the text there is
      selected on entry and the blue highlight covered the white. }
    DeTheme(TNewEdit(C));
    TNewEdit(C).Color := clSurface;
    TNewEdit(C).Font.Color := clFg;
    StripBorder(TNewEdit(C));
  end else if C is TNewCheckBox then begin
    { A themed checkbox draws its own label with the theme's text colour and ignores
      Font.Color entirely — which is why "Don't create a Start Menu folder" came out dark on
      a dark page and was effectively invisible. Dropping the theme hands the drawing back to
      the control, where Color and Font do apply. }
    DeTheme(TNewCheckBox(C));
    TNewCheckBox(C).Color := clBg;
    TNewCheckBox(C).Font.Color := clFg;
  end else if C is TNewRadioButton then begin
    DeTheme(TNewRadioButton(C));
    TNewRadioButton(C).Color := clBg;
    TNewRadioButton(C).Font.Color := clFg;
  end else if C is TNewStaticText then begin
    TNewStaticText(C).Color := clBg;
    TNewStaticText(C).Font.Color := clFg;
  end else if C is TNewLinkLabel then begin
    TNewLinkLabel(C).Color := clBg;
    TNewLinkLabel(C).Font.Color := clFg;
  end else if C is TLabel then begin
    TLabel(C).Transparent := True;
    TLabel(C).Font.Color := clFg;
  end else if C is TNewNotebookPage then begin
    TNewNotebookPage(C).Color := clBg;
  end else if C is TPanel then begin
    SolidPanel(TPanel(C), clBg);
  end;

  if C is TWinControl then
    PaintTree(TWinControl(C));
end;

procedure PaintTree(P: TWinControl);
var
  I: Integer;
begin
  for I := 0 to P.ControlCount - 1 do
    PaintOne(P.Controls[I]);
end;

{ ---- pass B: flat square buttons ------------------------------------------ }
{
  TNewButton is a themed Windows BUTTON: its Color is ignored by the renderer, and Inno's
  scripting wrapper exposes no ownerdraw hook. Removing the theme yields the grey Windows-95
  button, not a dark one.

  So each real button is PARKED off-screen rather than hidden. Visible stays True, which keeps
  the Default/Cancel handling and the Alt accelerators alive — Enter and Esc still work with
  no keyboard hooks. A hairline outline plus a dark face and a caption is drawn at the
  original bounds and forwards clicks with BM_CLICK, so the real button fires its real
  OnClick and every wizard behaviour is preserved.
}

procedure BtnClick(Sender: TObject);
var
  I: Integer;
begin
  for I := 0 to GetArrayLength(GBtnReal) - 1 do
    if (Sender = GBtnFace[I]) or (Sender = GBtnText[I]) then begin
      if GBtnReal[I].Enabled and GBtnReal[I].Visible then
        PostMessage(GBtnReal[I].Handle, BM_CLICK, 0, 0);
      Exit;
    end;
end;

{ Mirrors caption, enabled and visible from the real buttons onto the faces. Has to run
  whenever Inno changes them: Next becomes Install becomes Finish, buttons go dead during the
  copy, Back and Cancel disappear on the last page. }
procedure SkinButtons;
var
  I: Integer;
  S: String;
begin
  for I := 0 to GetArrayLength(GBtnReal) - 1 do begin
    S := GBtnReal[I].Caption;
    StringChangeEx(S, '&', '', True);
    GBtnText[I].Caption := S;
    GBtnText[I].Left := (GBtnFace[I].Width - GBtnText[I].Width) div 2;
    GBtnText[I].Top := (GBtnFace[I].Height - GBtnText[I].Height) div 2;
    GBtnFace[I].Parent.Visible := GBtnReal[I].Visible;
    GBtnFace[I].Enabled := GBtnReal[I].Enabled;
    if not GBtnReal[I].Enabled then begin
      GBtnFace[I].Color := clBg;
      GBtnText[I].Font.Color := clFgMuted;
    end else if GBtnReal[I] = WizardForm.NextButton then begin
      { The primary action is inverted — white face, black text — exactly as the app's own
        selected segmented button is. On a #0A0A0A page a #111111 face is invisible, and a
        wizard whose Next button cannot be found is worse than an unstyled one. }
      GBtnFace[I].Color := clFg;
      GBtnText[I].Font.Color := clBg;
    end else begin
      GBtnFace[I].Color := clSurface;
      GBtnText[I].Font.Color := clFg;
    end;
  end;
end;

procedure MakeFakeButton(B: TNewButton);
var
  N: Integer;
  Frame: TPanel;
begin
  N := GetArrayLength(GBtnReal);
  SetArrayLength(GBtnReal, N + 1);
  SetArrayLength(GBtnFace, N + 1);
  SetArrayLength(GBtnText, N + 1);
  GBtnReal[N] := B;

  Frame := TPanel.Create(B.Parent);
  Frame.Parent := B.Parent;
  Frame.SetBounds(B.Left - 1, B.Top - 1, B.Width + 2, B.Height + 2);
  SolidPanel(Frame, clLine);
  RememberLine(Frame);
  if B.Parent = WizardForm then
    Frame.Anchors := [akRight, akBottom];

  GBtnFace[N] := TPanel.Create(Frame);
  GBtnFace[N].Parent := Frame;
  GBtnFace[N].SetBounds(1, 1, B.Width, B.Height);
  SolidPanel(GBtnFace[N], clSurface);
  GBtnFace[N].Anchors := [akLeft, akTop, akRight, akBottom];
  GBtnFace[N].Cursor := crHand;
  GBtnFace[N].OnClick := @BtnClick;

  GBtnText[N] := TLabel.Create(GBtnFace[N]);
  GBtnText[N].Parent := GBtnFace[N];
  GBtnText[N].Transparent := True;
  GBtnText[N].AutoSize := True;
  GBtnText[N].Font := B.Font;
  GBtnText[N].Font.Color := clFg;
  GBtnText[N].Cursor := crHand;
  GBtnText[N].OnClick := @BtnClick;

  B.TabStop := False;
  B.Top := OFFSCREEN_TOP;
end;

{ Collects one parent's buttons before skinning them, so the child list is never mutated
  while it is being walked. }
procedure SkinTree(P: TWinControl);
var
  I, N: Integer;
  L: array of TNewButton;
begin
  N := 0;
  SetArrayLength(L, P.ControlCount);
  for I := 0 to P.ControlCount - 1 do
    if P.Controls[I] is TNewButton then begin
      L[N] := TNewButton(P.Controls[I]);
      N := N + 1;
    end else if P.Controls[I] is TWinControl then
      SkinTree(TWinControl(P.Controls[I]));
  for I := 0 to N - 1 do
    MakeFakeButton(L[I]);
end;

{ ---- events --------------------------------------------------------------- }

procedure InitializeWizard;
begin
  WizardForm.Color := clBg;
  WizardForm.Font.Color := clFg;

  PaintTree(WizardForm);

  Frame1px(WizardForm.DirEdit);
  Frame1px(WizardForm.GroupEdit);
  Frame1px(WizardForm.ReadyMemo);
  Frame1px(WizardForm.TasksList);
  Frame1px(WizardForm.ComponentsList);
  Frame1px(WizardForm.ProgressGauge);

  { The stock folder glyphs are full-colour Windows icons. A yellow folder is the one thing
    on screen that is not monochrome, so it goes; the indent it leaves reads as a margin.
    The header image is a TBitmapImage too — it is the K mark, and it stays. }
  WizardForm.SelectDirBitmapImage.Visible := False;
  WizardForm.SelectGroupBitmapImage.Visible := False;

  { our own hairline in place of the hidden stock bevel }
  NewLine(WizardForm, 0, WizardForm.CancelButton.Top - ScaleY(12),
    WizardForm.ClientWidth, 1).Anchors := [akLeft, akRight, akBottom];

  SkinTree(WizardForm);
  SkinButtons;
  ApplyDwm(WizardForm.Handle);
end;

{ Puts our own panels back after a repaint pass has painted them page-background. }
procedure RestoreLines;
var
  I: Integer;
begin
  for I := 0 to GetArrayLength(GLines) - 1 do
    GLines[I].Color := clLine;
end;

{ A page is restyled when it is first shown, not only at startup.
  Some controls are not in their final state during InitializeWizard — the Start Menu page's
  edit came back with a white background because whatever set it ran after our single pass.
  Repainting on entry is idempotent and costs nothing at page-change rate. }
procedure CurPageChanged(CurPageID: Integer);
begin
  PaintTree(WizardForm);
  RestoreLines;
  SkinButtons;
  ApplyDwm(WizardForm.Handle);
end;

procedure CurStepChanged(CurStep: TSetupStep);
begin
  SkinButtons;
end;

procedure CurInstallProgressChanged(CurProgress, MaxProgress: Integer);
begin
  SkinButtons;
end;

procedure InitializeUninstallProgressForm;
begin
  UninstallProgressForm.Color := clBg;
  UninstallProgressForm.Font.Color := clFg;
  PaintTree(UninstallProgressForm);
  SkinTree(UninstallProgressForm);
  SkinButtons;
  ApplyDwm(UninstallProgressForm.Handle);
end;

procedure CurUninstallStepChanged(CurUninstallStep: TUninstallStep);
var
  Settings: String;
begin
  if CurUninstallStep = usPostUninstall then
  begin
    { Only Market's own folder. The parent com.korawallet directory is shared, so removing it
      wholesale would take another Kora product's settings with it. }
    Settings := ExpandConstant('{userappdata}\com.korawallet\kora_widget');
    if DirExists(Settings) then
      DelTree(Settings, True, True, True);
  end;
end;
